const { GraphQLID, GraphQLString } = require("graphql");

const DataFields = {
  id: { type: GraphQLID },
  session_code: { type: GraphQLString },
  machine_code: { type: GraphQLString },
  p_id: { type: GraphQLString },
  name: { type: GraphQLString },
  m_name: { type: GraphQLString },
  l_name: { type: GraphQLString },
  address_l1: { type: GraphQLString },
  address_l2: { type: GraphQLString },
  city: { type: GraphQLString },
  state: { type: GraphQLString },
  country: { type: GraphQLString },
  history: { type: GraphQLString },
  height: { type: GraphQLString },
  weigth: { type: GraphQLString },
  age: { type: GraphQLString },
  gender: { type: GraphQLString },
  visit_number: { type: GraphQLString },
  visit_time: { type: GraphQLString },
  visit_date: { type: GraphQLString },
  session_duration: { type: GraphQLString },
  rl_ls_max_backward: { type: GraphQLString },
  mc_torque_for_rl_ls_backward: { type: GraphQLString },
  ll_ls_max_backward: { type: GraphQLString },
  mc_torque_for_ll_ls_backward: { type: GraphQLString },
  rl_us_max_forward: { type: GraphQLString },
  mc_torque_for_rl_ls_forward: { type: GraphQLString },
  rl_us_max_backward: { type: GraphQLString },
  mc_torque_for_rl_us_backward: { type: GraphQLString },
  ll_us_max_forward: { type: GraphQLString },
  mc_torque_for_ll_us_forward: { type: GraphQLString },
  ll_us_max_backward: { type: GraphQLString },
  total_avg_patient_effort_rl_ls: { type: GraphQLString },
  total_avg_patient_effort_ll_ls: { type: GraphQLString },
  total_avg_patient_effort_rl_us: { type: GraphQLString },
  total_avg_patient_effort_ll_us: { type: GraphQLString },
  max_walking_speed: { type: GraphQLString },
  unweigh_first_0_0_25t: { type: GraphQLString },
  unweigh_first_0_25_0_5t: { type: GraphQLString },
  unweigh_first_0_5_0_75t: { type: GraphQLString },
  unweigh_first_0_75_1t: { type: GraphQLString },
  tmt_speed_table: { type: GraphQLString },
  rl_ls_torque_table: { type: GraphQLString },
  rl_us_torque_table: { type: GraphQLString },
  ll_ls_torque_table: { type: GraphQLString },
  ll_us_torque_table: { type: GraphQLString },
  rl_ls_position_table: { type: GraphQLString },
  rl_us_position_table: { type: GraphQLString },
  ll_ls_position_table: { type: GraphQLString },
  ll_us_position_table: { type: GraphQLString },
  rl_ls_direction_table: { type: GraphQLString },
  rl_us_direction_table: { type: GraphQLString },
  ll_ls_direction_table: { type: GraphQLString },
  ll_us_direction_table: { type: GraphQLString },
  unweight_table: { type: GraphQLString },
  system_error_log: { type: GraphQLString },
  conclusion_of_session: { type: GraphQLString },
  data_uploaded_sess_det: { type: GraphQLString },
  createdAt: { type: GraphQLString },
  updatedAt: { type: GraphQLString },
};

module.exports = DataFields;
